//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuView.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DuView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   책을 지울 수 없어요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CannotDeleteBook {
            get {
                return ResourceManager.GetString("CannotDeleteBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   책을 옮길 수 없어요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CannotMoveBook {
            get {
                return ResourceManager.GetString("CannotMoveBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   책을 열 수 없어요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CannotOpenBook {
            get {
                return ResourceManager.GetString("CannotOpenBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   디렉토리를 열 수 없어요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CannotOpenDirectory {
            get {
                return ResourceManager.GetString("CannotOpenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기억한 책을 열 수 없어요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CannotOpenRemember {
            get {
                return ResourceManager.GetString("CannotOpenRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   책 이름을 바꿀 수 없어요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CannotRenameBook {
            get {
                return ResourceManager.GetString("CannotRenameBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   책을 먼저 닫으세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CloseBookFirst {
            get {
                return ResourceManager.GetString("CloseBookFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DuView is a book viewer\n\n\n\n서시\n윤동주\n\n\n죽는 날까지 하늘을 우러러\n한 점 부끄럼이 없기를,\n잎새에 이는 바람에도\n나는 괴로워했다.\n\n\n별을 노래하는 마음으로\n모든 죽어 가는 것을 사랑해야지\n그리고 나한테 주어진 길을\n걸어가야겠다.\n\n\n오늘 밤에도 별이 바람에 스치운다.\n\n\n\n\nSupported by kshman\n,과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreditsWithSeosi {
            get {
                return ResourceManager.GetString("CreditsWithSeosi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   책 지우기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteBook {
            get {
                return ResourceManager.GetString("DeleteBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계속하시나요?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DoYouWannaContinue {
            get {
                return ResourceManager.GetString("DoYouWannaContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   두뷰과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DuView {
            get {
                return ResourceManager.GetString("DuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap folder_blue {
            get {
                object obj = ResourceManager.GetObject("folder-blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap housebari_head_128 {
            get {
                object obj = ResourceManager.GetObject("housebari_head_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   압축 파일이예요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IsArchive {
            get {
                return ResourceManager.GetString("IsArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   디렉토리예요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IsDirectory {
            get {
                return ResourceManager.GetString("IsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   책이 없어요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoBook {
            get {
                return ResourceManager.GetString("NoBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   외부 실행 파일이 없거나 실패했어요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoExternalRunExist {
            get {
                return ResourceManager.GetString("NoExternalRunExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 책이 없어요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoNextBook {
            get {
                return ResourceManager.GetString("NoNextBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이전 책이 없어요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoPreviousBook {
            get {
                return ResourceManager.GetString("NoPreviousBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   책 열기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpenBook {
            get {
                return ResourceManager.GetString("OpenBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ouch_noimg {
            get {
                object obj = ResourceManager.GetObject("ouch_noimg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   파일 이름을 기억했어요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RememberFilename {
            get {
                return ResourceManager.GetString("RememberFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   책을 기억할껀가요?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaveRememberBook {
            get {
                return ResourceManager.GetString("SaveRememberBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   책이나 이미지를 고르세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectBookOrImage {
            get {
                return ResourceManager.GetString("SelectBookOrImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   압축 파일|*.zip|모든 파일|*.*과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectFilter {
            get {
                return ResourceManager.GetString("SelectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체 페이지:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TotalPagesColon {
            get {
                return ResourceManager.GetString("TotalPagesColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지원하지 않는 압축 파일이예요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UnsupportArchive {
            get {
                return ResourceManager.GetString("UnsupportArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap viewmode_l2r {
            get {
                object obj = ResourceManager.GetObject("viewmode_l2r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap viewmode_none {
            get {
                object obj = ResourceManager.GetObject("viewmode_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap viewmode_pitwidth {
            get {
                object obj = ResourceManager.GetObject("viewmode_pitwidth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap viewmode_r2l {
            get {
                object obj = ResourceManager.GetObject("viewmode_r2l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
