//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuView.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DuView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   DuView is a book viewer\n\n\n\n서시\n윤동주\n\n\n죽는 날까지 하늘을 우러러\n한 점 부끄럼이 없기를,\n잎새에 이는 바람에도\n나는 괴로워했다.\n\n\n별을 노래하는 마음으로\n모든 죽어 가는 것을 사랑해야지\n그리고 나한테 주어진 길을\n걸어가야겠다.\n\n\n오늘 밤에도 별이 바람에 스치운다.\n\n\n\n\nSupported by kshman\n,과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreditsWithSeosi {
            get {
                return ResourceManager.GetString("CreditsWithSeosi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap folder_blue {
            get {
                object obj = ResourceManager.GetObject("folder-blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap housebari_head_128 {
            get {
                object obj = ResourceManager.GetObject("housebari_head_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   # English messages
        ///LANG=English
        ///
        ///0=DuView
        ///1=PuruLive
        ///2=https://github.com/kshman/DuView
        ///94=Close
        ///95=Menu
        ///96=Do you want to continue?
        ///97=Ok
        ///98=Cancel
        ///99=(reserved)
        ///
        ///101=Copy image
        ///102=Copied to clipboard!
        ///103=Fail to copying image to clipboard!
        ///104=Select an archive or image
        ///105=Archive|*.zip|All files|*.*
        ///106=Open book
        ///107=Cannot open the archive file!
        ///108=Cannot acces directory!
        ///109=No previous book!
        ///110=No next book!
        ///111=View book
        ///112=Image drawing error!
        ///113=file is archive file [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string locale_english {
            get {
                return ResourceManager.GetString("locale_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   # 한국말 메시지
        ///LANG=한국말
        ///
        ///0=두뷰
        ///1=PuruLive
        ///2=https://github.com/kshman/DuView
        ///94=닫기
        ///95=메뉴
        ///96=계속하시겠습니까?
        ///97=선택
        ///98=취소
        ///99=(기능없음)
        ///
        ///101=이미지 복사
        ///102=클립보드로 복사했어요!
        ///103=클립보드에 넣을 수 없어요!
        ///104=책이나 이미지를 고르세요
        ///105=압축 파일|*.zip|모든 파일|*.*
        ///106=책 열기
        ///107=열 수 없는 압축 파일이예요!
        ///108=디렉토리를 열 수 없어요!
        ///109=이전 책이 없어요!
        ///110=다음 책이 없어요!
        ///111=책 보기
        ///112=이미지 그리기 오류!
        ///113=파일은 압축 파일이예요
        ///114=책 지우기
        ///115=책을 지울 수 없었어요
        ///116=디렉토리예요
        ///117=책을 열 수 없어요
        ///118=찾아보기
        ///119=실행 파일|*.exe
        ///120=적절한 파일을 고르세요
        ///121=외부 실행 파일이 없거나 실패했어요
        ///122=책 이름 바꾸기
        ///123=책 이름을 바꿀 [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string locale_korean {
            get {
                return ResourceManager.GetString("locale_korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2022-11-30 21:14과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LocaleLastCheck {
            get {
                return ResourceManager.GetString("LocaleLastCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ouch_noimg {
            get {
                object obj = ResourceManager.GetObject("ouch_noimg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap viewmode_l2r {
            get {
                object obj = ResourceManager.GetObject("viewmode_l2r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap viewmode_none {
            get {
                object obj = ResourceManager.GetObject("viewmode_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap viewmode_pitwidth {
            get {
                object obj = ResourceManager.GetObject("viewmode_pitwidth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap viewmode_r2l {
            get {
                object obj = ResourceManager.GetObject("viewmode_r2l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
