//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuView.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DuView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap housebari_head_128 {
            get {
                object obj = ResourceManager.GetObject("housebari_head_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # English messages
        ///LANG=English
        ///
        ///0=DuView
        ///1=PuruLive
        ///2=https://github.com/kshman/DuView
        ///95=Menu
        ///96=Do you want to continue?
        ///97=Ok
        ///98=Cancel
        ///99=(reserved)
        ///
        ///101=Copy image
        ///102=Copied to clipboard!
        ///103=Fail to copying image to clipboard!
        ///104=Select archive or image
        ///105=Archive|*.zip|All files|*.*
        ///106=Open book
        ///107=Cannot open archive file!
        ///108=Cannot acces directory!
        ///109=No previous book!
        ///110=No next book!
        ///111=View book
        ///112=Image drawing error!
        ///113=file is archive file 
        ///114=Delete book [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string locale_english {
            get {
                return ResourceManager.GetString("locale_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # 한국말 메시지
        ///LANG=한국말
        ///
        ///0=두뷰
        ///1=PuruLive
        ///2=https://github.com/kshman/DuView
        ///95=메뉴
        ///96=계속하시겠습니까?
        ///97=선택
        ///98=취소
        ///99=(기능없음)
        ///
        ///101=이미지 복사
        ///102=클립보드로 복사했습니다!
        ///103=클립보드에 넣을 수 없습니다!
        ///104=책이나 이미지를 고르세요
        ///105=압축 파일|*.zip|모든 파일|*.*
        ///106=책 열기
        ///107=열 수 없는 압축 파일입니다!
        ///108=디렉토리를 열 수 없어요!
        ///109=이전 책이 없어요!
        ///110=다음 책이 없어요!
        ///111=책 보기
        ///112=이미지 그리기 오류!
        ///113=파일은 압축 파일입니다. 
        ///114=책 지우기
        ///115=책을 지울 수 없었습니다
        ///116=디렉토리입니다.
        ///
        ///# 보기(1100)
        ///1100=보기(&amp;V)
        ///1101=늘려보기(&amp;Z)
        ///1102=그림 품질
        ///1103=가로 맞춤(&amp;W)
        ///1104=세로 맞춤(&amp;H)
        ///1105=왼쪽 → 오른쪽(&amp;L)
        ///1106=오른쪽 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string locale_korean {
            get {
                return ResourceManager.GetString("locale_korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ouch_noimg {
            get {
                object obj = ResourceManager.GetObject("ouch_noimg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap viewmode_l2r {
            get {
                object obj = ResourceManager.GetObject("viewmode_l2r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap viewmode_none {
            get {
                object obj = ResourceManager.GetObject("viewmode_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap viewmode_pitwidth {
            get {
                object obj = ResourceManager.GetObject("viewmode_pitwidth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap viewmode_r2l {
            get {
                object obj = ResourceManager.GetObject("viewmode_r2l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
